// Every raid boss's own drawn parts (<motif>.parts.jsx), gathered for impact/parts.jsx.
import chronosParts, { css as chronosCss } from './chronos.parts'
import bansheeParts, { css as bansheeCss } from './banshee.parts'
import seraphParts, { css as seraphCss } from './seraph.parts'
import titanParts, { css as titanCss } from './titan.parts'
import vampireParts, { css as vampireCss } from './vampire.parts'
import gorgonParts, { css as gorgonCss } from './gorgon.parts'
import chimeraParts, { css as chimeraCss } from './chimera.parts'
import ratkingParts, { css as ratkingCss } from './ratking.parts'
import showmanParts, { css as showmanCss } from './showman.parts'
import reaperParts, { css as reaperCss } from './reaper.parts'
import leviathanParts, { css as leviathanCss } from './leviathan.parts'
import lichParts, { css as lichCss } from './lich.parts'
import cerberusParts, { css as cerberusCss } from './cerberus.parts'
import tempestParts, { css as tempestCss } from './tempest.parts'
import dreamerParts, { css as dreamerCss } from './dreamer.parts'
import berserkerParts, { css as berserkerCss } from './berserker.parts'
import infernoParts, { css as infernoCss } from './inferno.parts'
import swarmqueenParts, { css as swarmqueenCss } from './swarmqueen.parts'
import moonmawParts, { css as moonmawCss } from './moonmaw.parts'
import hydraParts, { css as hydraCss } from './hydra.parts'
import kaleidoParts, { css as kaleidoCss } from './kaleido.parts'
import puppeteerParts, { css as puppeteerCss } from './puppeteer.parts'
import sugarqueenParts, { css as sugarqueenCss } from './sugarqueen.parts'
import kitsuneParts, { css as kitsuneCss } from './kitsune.parts'
import ophanimParts, { css as ophanimCss } from './ophanim.parts'
import voidParts, { css as voidCss } from './void.parts'
export const BOSS_PARTS = { ...chronosParts, ...bansheeParts, ...seraphParts, ...titanParts, ...vampireParts, ...gorgonParts, ...chimeraParts, ...ratkingParts, ...showmanParts, ...reaperParts, ...leviathanParts, ...lichParts, ...cerberusParts, ...tempestParts, ...dreamerParts, ...berserkerParts, ...infernoParts, ...swarmqueenParts, ...moonmawParts, ...hydraParts, ...kaleidoParts, ...puppeteerParts, ...sugarqueenParts, ...kitsuneParts, ...ophanimParts, ...voidParts }
export const BOSS_PARTS_CSS = [chronosCss, bansheeCss, seraphCss, titanCss, vampireCss, gorgonCss, chimeraCss, ratkingCss, showmanCss, reaperCss, leviathanCss, lichCss, cerberusCss, tempestCss, dreamerCss, berserkerCss, infernoCss, swarmqueenCss, moonmawCss, hydraCss, kaleidoCss, puppeteerCss, sugarqueenCss, kitsuneCss, ophanimCss, voidCss].join(' ')
