// Every raid boss's own fight moments (impact/bosses/<motif>.js) and drawn parts (<motif>.parts.jsx), gathered.
import chronos from './chronos'
import banshee from './banshee'
import seraph from './seraph'
import titan from './titan'
import vampire from './vampire'
import gorgon from './gorgon'
import chimera from './chimera'
import ratking from './ratking'
import showman from './showman'
import reaper from './reaper'
import leviathan from './leviathan'
import lich from './lich'
import cerberus from './cerberus'
import tempest from './tempest'
import dreamer from './dreamer'
import berserker from './berserker'
import inferno from './inferno'
import swarmqueen from './swarmqueen'
import moonmaw from './moonmaw'
import hydra from './hydra'
import kaleido from './kaleido'
import puppeteer from './puppeteer'
import sugarqueen from './sugarqueen'
import kitsune from './kitsune'
import ophanim from './ophanim'
import voidBoss from './void'
export const BOSS_DATA = { chronos, banshee, seraph, titan, vampire, gorgon, chimera, ratking, showman, reaper, leviathan, lich, cerberus, tempest, dreamer, berserker, inferno, swarmqueen, moonmaw, hydra, kaleido, puppeteer, sugarqueen, kitsune, ophanim, void: voidBoss }
