// RAID IMPACT STYLES (pure data, tested by impact.test.js): how each raid boss's plain fight moments look, so a hit, a
// critical, the boss's strike and its knockout read as THAT boss (the owner: "make sure all of these hit hard and are
// unique per raid boss"). The moments themselves come from strikeFx.js; the parts are drawn by impact/parts.jsx.
//   color / accent   the boss's two fixed impact colors (bright, both themes; never theme tokens over the art)
//   glyph            its particle (impact/glyphs.jsx), flung by its hits and its knockout
//   hit              parts played when the player strikes it
//   crit             a critical: its own burst plus its own starburst (points, spin)
//   sharpen          a Sharpened strike: honed blades (angle, count, fan) and the boss's own flavor
//   strike           its own attack on the player (a plain miss)
//   heavy            a missed ATTACK: a bigger, different blow (the ground quakes) than its plain strike
//   block            the player blocked its attack: its own barrier sigil (sides, turn) and what flies off it
//   shield           a Shield saved the heart: the dome, its own glyphs glancing off it
//   wind             Second wind: the heart rising and the boss's own flourish
//   ko               its knockout: a staged CINEMATIC (each part's `at`, ms), that boss's own death told in parts
//   koMs / koPeak    how long the knockout plays and when its climax lands (the shockwave, then the DEFEATED stamp)
//   body             one move per moment (impact/body.js BODY_KEYFRAMES; BossArena plays the strike moment's own)
// EVERY MOMENT LOOKS DIFFERENT (the owner: "every impact needs to be different"): within a boss no two of the 9
// moments share a part list or a body move, and across bosses no two share a moment's part list (impact.test.js).
// A part is [name, params]; parts.jsx knows every name (PARTS).
import { BODY_KEYFRAMES } from './body'
export const MOMENT_KEYS = ['hit', 'crit', 'sharpen', 'strike', 'heavy', 'block', 'shield', 'wind', 'ko']
export const BODY = Object.fromEntries(Object.entries(BODY_KEYFRAMES).map(([k, v]) => [k, Object.keys(v)]))

export const RAID_IMPACT = {
  chronos: {
    color: '#f2c14e', accent: '#7a4a12', glyph: 'gear',
    hit: [['burst', { n: 6, spin: 240 }], ['sparks', { n: 6 }], ['ring', {}]],
    crit: [['burst', { n: 10, spin: 360, size: 1.3 }], ['hands', { ms: 700 }], ['starburst', { points: 12, inner: 0.7, spin: 30 }]],
    strike: [['hands', { ms: 620 }], ['burst', { n: 14, glyph: 'grain', size: 0.4, reach: 1.1 }], ['vignette', {}]],
    ko: [['speedlines', { color: '#fff2b0', n: 36 }], ['flash', { big: true }], ['dial', { at: 150 }], ['hands', { at: 250, ms: 1000 }], ['crack', { at: 900, n: 8 }],
      ['shards', { at: 1300, n: 18, color: '#dff6ff', reach: 1.3 }], ['ring', { at: 1300, scale: 2.4, width: 6 }], ['burst', { at: 1350, n: 10, spin: 540, size: 1.1 }], ['drops', { at: 1450, n: 16, glyph: 'grain', size: 0.45 }]],
    koMs: 2200, koPeak: 1300,
    sharpen: [['blade', { angle: -20, n: 2, color: '#ffe9a0' }], ['glint', { n: 6, color: '#fff2b0' }], ['burst', { n: 5, glyph: 'grain', size: 0.5, spin: 180 }]],
    heavy: [['quake', { n: 3 }], ['pillar', { width: 0.25 }], ['drops', { n: 18, glyph: 'grain', size: 0.45 }], ['crack', { n: 5 }]],
    block: [['sigil', { sides: 12, turn: 60 }], ['sparks', { n: 12, color: '#fff2b0' }]],
    shield: [['bubble', {}], ['deflect', { n: 5 }]],
    wind: [['heart', {}], ['gust', { n: 3, color: '#ffd27a', turn: -90 }]],
    body: { hit: 'clank', crit: 'stun', sharpen: 'nick', strike: 'rear', heavy: 'loom', block: 'jar', shield: 'rebuff', wind: 'dim', ko: 'timeStop' },
  },
  banshee: {
    color: '#7ff0ff', accent: '#0b3a46', glyph: 'note',
    hit: [['burst', { n: 6, spin: 60 }], ['ring', { dashed: true }]],
    crit: [['burst', { n: 10, spin: 90, size: 1.3 }], ['scream', { n: 2 }], ['starburst', { points: 5, inner: 0.35, spin: 15 }]],
    strike: [['scream', { n: 4 }], ['vignette', { color: '#46d6ff' }]],
    ko: [['speedlines', { color: '#c8fbff', n: 48, rot: 4 }], ['flash', { big: true }], ['scream', { at: 100, n: 4 }], ['flatline', { at: 350 }],
      ['ring', { at: 1100, dashed: true, scale: 2.6, width: 4 }], ['smoke', { at: 1100, color: '#bff6ff', n: 8 }], ['rise', { at: 1150, n: 12, glyph: 'note' }]],
    koMs: 2000, koPeak: 1100,
    sharpen: [['blade', { angle: 10, n: 3, color: '#c8fbff', fan: 14 }], ['ring', { color: '#c8fbff', dashed: true, scale: 1.4 }]],
    heavy: [['pull', { n: 14, glyph: 'note' }], ['quake', { n: 1, color: '#7ff0ff' }], ['vignette', { color: '#0b8fb0' }]],
    block: [['sigil', { sides: 5, turn: -40 }], ['rise', { n: 8, glyph: 'note', size: 0.6 }]],
    shield: [['bubble', {}], ['deflect', { n: 4, from: 'side' }], ['scream', { n: 1, inward: true }]],
    wind: [['heart', {}], ['pulse', { color: '#7ff0ff' }], ['gust', { n: 2, color: '#c8fbff', turn: -45 }]],
    body: { hit: 'flicker', crit: 'jolt', sharpen: 'sever', strike: 'scream', heavy: 'charge', block: 'reel', shield: 'glance', wind: 'sway', ko: 'silence' },
  },
  seraph: {
    color: '#ffe79a', accent: '#b8862b', glyph: 'feather',
    hit: [['burst', { n: 6, spin: 120 }], ['sparks', { n: 8, color: '#fffbe6' }]],
    crit: [['burst', { n: 10, spin: 180, size: 1.3 }], ['pillar', { width: 0.3, color: '#ffb300' }], ['starburst', { points: 8, inner: 0.25, spin: 45 }]],
    strike: [['beam', { dir: 'down', width: 0.5, color: '#ffb300' }], ['drops', { n: 8, glyph: 'feather', size: 0.6 }], ['ring', { color: '#ffb300', scale: 2, width: 4 }]],
    ko: [['speedlines', { color: '#fffbe6', n: 30, rot: 6 }], ['flash', { big: true }], ['pillar', { at: 150, width: 0.7, color: '#ffb300' }], ['wings', { at: 300 }],
      ['rise', { at: 1050, n: 16, glyph: 'ember', size: 0.4, color: '#ffb300' }], ['rays', { at: 1350, n: 18 }], ['ring', { at: 1350, color: '#ffe79a', scale: 2.6, width: 5 }], ['drops', { at: 1400, n: 14, glyph: 'feather', size: 0.6 }]],
    koMs: 2300, koPeak: 1350,
    sharpen: [['blade', { angle: -60, n: 2, color: '#fffbe6' }], ['rays', { n: 8, color: '#ffe79a' }]],
    heavy: [['drops', { n: 20, glyph: 'feather', size: 0.7 }], ['rays', { n: 10, color: '#ffb300' }], ['quake', { n: 2, color: '#ffe79a' }]],
    block: [['sigil', { sides: 8, turn: 22 }], ['glint', { n: 7, color: '#fffbe6' }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'feather' }], ['glint', { n: 4 }]],
    wind: [['heart', {}], ['pulse', { color: '#ffe79a' }], ['rise', { n: 5, glyph: 'feather', size: 0.5 }]],
    body: { hit: 'flinch', crit: 'whiplash', sharpen: 'carve', strike: 'cast', heavy: 'loom', block: 'recoil', shield: 'rebuff', wind: 'falter', ko: 'fallFromGrace' },
  },
  titan: {
    color: '#ff7a1c', accent: '#3a1a08', glyph: 'fist',
    hit: [['burst', { n: 5, glyph: 'nut', size: 0.7, spin: 300 }], ['sparks', { n: 10, color: '#ffd27a' }]],
    crit: [['sparks', { n: 18, color: '#ffe0a0', reach: 1.2 }], ['ring', { scale: 2.2, width: 5 }], ['crack', { n: 4 }], ['starburst', { points: 6, inner: 0.55, spin: 0 }]],
    strike: [['slam', { glyph: 'fist' }], ['crack', { n: 5 }], ['dust', { n: 10 }]],
    ko: [['speedlines', { color: '#ffd27a', n: 32 }], ['flash', { big: true }], ['popchain', { at: 200, n: 6 }], ['sparks', { at: 300, n: 18, color: '#ffe0a0', reach: 1.2 }],
      ['crack', { at: 1450, n: 9 }], ['dust', { at: 1550, n: 18 }], ['ring', { at: 1550, scale: 2.8, width: 7 }], ['burst', { at: 1600, glyph: 'nut', n: 12, spin: 400, reach: 1.3 }]],
    koMs: 2400, koPeak: 1550,
    sharpen: [['blade', { angle: 0, n: 1, color: '#ffd27a', ms: 380 }], ['sparks', { n: 22, color: '#ffe0a0', reach: 1.3 }]],
    heavy: [['quake', { n: 3, rubble: 10 }], ['crack', { n: 8 }], ['sparks', { n: 18, color: '#ffd27a', reach: 1.4 }], ['dust', { n: 14 }]],
    block: [['sigil', { sides: 6, turn: 0 }], ['burst', { n: 6, glyph: 'nut', size: 0.6, spin: 400 }]],
    shield: [['bubble', {}], ['deflect', { n: 3, glyph: 'fist' }]],
    wind: [['heart', {}], ['dust', { n: 10, color: '#ffd27a' }], ['gust', { n: 3, color: '#ff7a1c', turn: 70 }]],
    body: { hit: 'clank', crit: 'buckle', sharpen: 'nick', strike: 'slam', heavy: 'crush', block: 'jar', shield: 'skid', wind: 'shrink', ko: 'topple' },
  },
  vampire: {
    color: '#ff2442', accent: '#2a0008', glyph: 'bat',
    hit: [['burst', { n: 5, size: 0.8, spin: 30 }], ['drops', { n: 6, glyph: 'drop', size: 0.4, color: '#c8001e' }]],
    crit: [['burst', { n: 10, size: 1, spin: 40 }], ['fangs', { n: 2, small: true }], ['starburst', { points: 7, inner: 0.3, spin: -60 }]],
    strike: [['fangs', { n: 2 }], ['drops', { n: 10, glyph: 'drop', size: 0.5, color: '#c8001e' }], ['vignette', {}]],
    ko: [['speedlines', { color: '#ff8a9a', n: 44, rot: 2 }], ['flash', { big: true }], ['charge', { at: 200, glyph: 'drop', color: '#ff2442' }], ['smoke', { at: 1000, dir: 'out', color: '#c8001e', n: 12 }],
      ['splat', { at: 1150, n: 12, color: '#c8001e', big: true, reach: 1.2 }], ['rise', { at: 1150, n: 20, glyph: 'bat', size: 0.9 }], ['burst', { at: 1200, n: 12, spin: 60, reach: 1.4 }], ['ring', { at: 1200, scale: 2.4, color: '#ff2442' }]],
    koMs: 2100, koPeak: 1200,
    sharpen: [['blade', { angle: 35, n: 2, color: '#ff8a9a' }], ['drops', { n: 5, glyph: 'drop', size: 0.35, color: '#c8001e' }]],
    heavy: [['claws', { n: 4, angle: -20, color: '#ff2442' }], ['splat', { n: 8, color: '#c8001e', big: true }], ['quake', { n: 1, color: '#8a0016' }]],
    block: [['sigil', { sides: 4, rot: 45, turn: 90 }], ['burst', { n: 5, glyph: 'bat', size: 0.6, spin: 40 }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'bat', from: 'side' }]],
    wind: [['heart', {}], ['rise', { n: 6, glyph: 'drop', size: 0.4, color: '#ff6b8a' }], ['gust', { n: 3, color: '#ff2442', turn: -130 }]],
    body: { hit: 'flinch', crit: 'twirl', sharpen: 'gash', strike: 'dart', heavy: 'pounce', block: 'stumble', shield: 'ricochet', wind: 'dim', ko: 'batBurst' },
  },
  gorgon: {
    color: '#3fe08a', accent: '#0d3a1f', glyph: 'scale',
    hit: [['burst', { n: 6, spin: 90 }], ['ring', { color: '#9fffc8' }]],
    crit: [['burst', { n: 10, spin: 120, size: 1.2 }], ['beam', { dir: 'cone', width: 0.5, small: true }], ['starburst', { points: 10, inner: 0.5, spin: 70 }]],
    strike: [['beam', { dir: 'cone', width: 0.9 }], ['crack', { n: 5, color: '#c9d1cc' }]],
    ko: [['speedlines', { color: '#9fffc8', n: 38, rot: 3 }], ['flash', { big: true }], ['front', { at: 200, ms: 1100 }], ['crack', { at: 1350, n: 10, color: '#c9d1cc' }],
      ['dust', { at: 1450, n: 16, color: '#a7b0aa' }], ['drops', { at: 1450, n: 16, glyph: 'rubble', size: 0.6, color: '#8b938e' }], ['burst', { at: 1500, n: 10, spin: 120 }], ['ring', { at: 1450, color: '#c9d1cc', scale: 2.4, width: 5 }]],
    koMs: 2300, koPeak: 1450,
    sharpen: [['blade', { angle: -45, n: 3, color: '#9fffc8', fan: 30 }], ['shards', { n: 6, color: '#9fffc8' }]],
    heavy: [['scream', { n: 3, color: '#3fe08a' }], ['quake', { n: 2, color: '#c9d1cc', rubble: 8 }], ['dust', { n: 12, color: '#a7b0aa' }]],
    block: [['sigil', { sides: 3, turn: 120 }], ['shards', { n: 8, color: '#c9d1cc', inward: true }]],
    shield: [['bubble', {}], ['deflect', { n: 4, glyph: 'scale' }], ['crack', { n: 3, color: '#c9d1cc' }]],
    wind: [['heart', {}], ['gust', { n: 2, color: '#3fe08a', turn: 80 }]],
    body: { hit: 'flinch', crit: 'stun', sharpen: 'split', strike: 'rear', heavy: 'loom', block: 'reel', shield: 'rebuff', wind: 'sway', ko: 'stoneSet' },
  },
  chimera: {
    color: '#ff6a2a', accent: '#3b0f00', glyph: 'claw',
    hit: [['burst', { n: 5, spin: 40 }], ['sparks', { n: 8 }]],
    crit: [['claws', { n: 3, angle: -30, small: true }], ['burst', { n: 9, size: 1.2 }], ['starburst', { points: 3, inner: 0.4, spin: 120 }]],
    strike: [['bite', { n: 3, dir: 'v' }], ['vignette', {}]],
    ko: [['speedlines', { color: '#ffb36a', n: 34, rot: 5 }], ['flash', { big: true }], ['roar', { at: 280, color: '#ff6a2a', spikes: 11 }], ['roar', { at: 630, color: '#f2e6c8', spikes: 8, turn: -30 }],
      ['roar', { at: 980, color: '#5dff8a', spikes: 15, turn: 40 }], ['dust', { at: 1400, n: 16 }], ['ring', { at: 1400, scale: 2.6, color: '#ff6a2a', width: 6 }], ['burst', { at: 1450, n: 10, spin: 90 }]],
    koMs: 2300, koPeak: 1400,
    sharpen: [['blade', { angle: -10, n: 3, color: '#ffb36a', fan: 40 }], ['claws', { n: 2, angle: 30, small: true }]],
    heavy: [['claws', { n: 5, angle: 15 }], ['breath', {}], ['quake', { n: 1 }]],
    block: [['sigil', { sides: 3, rot: 180, turn: -60 }], ['sparks', { n: 10, color: '#ffb36a' }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'claw' }]],
    wind: [['heart', {}], ['rise', { n: 8, glyph: 'ember', size: 0.35, color: '#ffb36a' }]],
    body: { hit: 'reel', crit: 'knock', sharpen: 'carve', strike: 'lunge', heavy: 'pounce', block: 'stumble', shield: 'glance', wind: 'falter', ko: 'threeRoars' },
  },
  ratking: {
    color: '#ffc93a', accent: '#7a4f00', glyph: 'coin',
    hit: [['burst', { n: 6, spin: 720, size: 0.8 }], ['sparks', { n: 6, color: '#fff2b0' }]],
    crit: [['burst', { n: 14, spin: 900, size: 0.9, reach: 1.2 }], ['ring', { scale: 2 }], ['starburst', { points: 16, inner: 0.8, spin: 90 }]],
    strike: [['whip', { color: '#c98f86' }], ['burst', { n: 8, spin: 720, size: 0.6 }], ['vignette', {}]],
    ko: [['speedlines', { color: '#fff2b0', n: 30, rot: 7 }], ['flash', { big: true }], ['crown', { at: 200 }], ['fountain', { at: 950, n: 26, glyph: 'coin', size: 0.7 }],
      ['ring', { at: 1300, scale: 2.6, width: 5 }], ['sparks', { at: 1300, n: 14, color: '#fff2b0', reach: 1.3 }], ['burst', { at: 1350, n: 12, spin: 900, reach: 1.4, size: 0.8 }]],
    koMs: 2200, koPeak: 1300,
    sharpen: [['blade', { angle: 25, n: 2, color: '#fff2b0' }], ['fountain', { n: 10, glyph: 'coin', size: 0.5 }]],
    heavy: [['drops', { n: 20, glyph: 'coin', size: 0.55 }], ['claws', { n: 3, color: '#c98f86' }], ['quake', { n: 2 }]],
    block: [['sigil', { sides: 10, turn: 36 }], ['burst', { n: 10, glyph: 'coin', size: 0.5, spin: 900 }]],
    shield: [['bubble', {}], ['deflect', { n: 7, glyph: 'coin' }]],
    wind: [['heart', {}], ['glint', { n: 8, color: '#ffe68a', size: 0.8 }]],
    body: { hit: 'spin', crit: 'twirl', sharpen: 'nick', strike: 'swipe', heavy: 'charge', block: 'rebound', shield: 'skid', wind: 'shrink', ko: 'dethroned' },
  },
  showman: {
    color: '#ff4fb0', accent: '#ffffff', glyph: 'card',
    hit: [['burst', { n: 5, spin: 540, size: 0.8 }], ['confetti', { n: 10 }]],
    crit: [['burst', { n: 9, spin: 720 }], ['confetti', { n: 22 }], ['starburst', { points: 5, inner: 0.5, spin: 216 }]],
    strike: [['cards', { n: 7 }], ['vignette', { color: '#ff4fb0' }]],
    ko: [['speedlines', { color: '#ffd6ee', n: 26, rot: 9 }], ['flash', { big: true }], ['spotlight', { at: 150, color: '#fff4c0' }], ['curtain', { at: 650, part: 36 }],
      ['confetti', { at: 1500, n: 44, reach: 1.5 }], ['burst', { at: 1500, n: 12, spin: 900, reach: 1.3 }], ['ring', { at: 1550, color: '#ff4fb0', scale: 2.4, dashed: true }]],
    koMs: 2400, koPeak: 1500,
    sharpen: [['blade', { angle: -35, n: 4, color: '#ffd6ee', fan: 18, gap: 60 }], ['cards', { n: 4 }]],
    heavy: [['rays', { n: 12, color: '#ff4fb0' }], ['volley', { n: 14 }], ['quake', { n: 1, color: '#ff4fb0' }]],
    block: [['sigil', { sides: 4, turn: 180 }], ['confetti', { n: 14 }]],
    shield: [['bubble', {}], ['deflect', { n: 5, glyph: 'card', from: 'side' }]],
    wind: [['heart', {}], ['glint', { n: 8, color: '#ffd6ee' }], ['gust', { n: 2, color: '#ff4fb0', turn: 140 }]],
    body: { hit: 'spin', crit: 'twirl', sharpen: 'split', strike: 'cast', heavy: 'overreach', block: 'rebound', shield: 'glance', wind: 'sway', ko: 'curtainCall' },
  },
  reaper: {
    color: '#6fe3ff', accent: '#06222c', glyph: 'wisp',
    hit: [['burst', { n: 5, spin: 20 }], ['ring', { color: '#bff4ff' }]],
    crit: [['arc', { small: true }], ['burst', { n: 9, spin: 40 }], ['starburst', { points: 4, inner: 0.2, spin: 45 }]],
    strike: [['arc', {}], ['vignette', { color: '#3fb8d6' }]],
    ko: [['speedlines', { color: '#bff4ff', n: 42, rot: 8 }], ['flash', { big: true }], ['scythe', { at: 150 }], ['rise', { at: 1150, n: 16, glyph: 'wisp', size: 0.9 }],
      ['smoke', { at: 1200, color: '#6fe3ff', n: 8 }], ['ring', { at: 1250, color: '#bff4ff', dashed: true, scale: 2.2, width: 4 }], ['shards', { at: 1300, n: 10, color: '#e8fbff' }]],
    koMs: 2200, koPeak: 1250,
    sharpen: [['blade', { angle: -70, n: 1, color: '#e8fbff', ms: 520 }], ['arc', { small: true, reverse: true }]],
    heavy: [['cleave', {}], ['rise', { n: 10, glyph: 'wisp', size: 0.7 }], ['quake', { n: 2, color: '#3fb8d6' }]],
    block: [['sigil', { sides: 7, turn: -51 }], ['sparks', { n: 8, color: '#bff4ff' }]],
    shield: [['bubble', {}], ['deflect', { n: 4, glyph: 'wisp', from: 'side' }]],
    wind: [['heart', {}], ['pulse', { color: '#6fe3ff' }]],
    body: { hit: 'reel', crit: 'whiplash', sharpen: 'sever', strike: 'swipe', heavy: 'overreach', block: 'recoil', shield: 'glance', wind: 'dim', ko: 'reaped' },
  },
  leviathan: {
    color: '#38b6ff', accent: '#e8f8ff', glyph: 'drop',
    hit: [['burst', { n: 7, size: 0.7 }], ['splat', { n: 5, color: '#9fdcff' }]],
    crit: [['wave', { small: true }], ['burst', { n: 10, size: 0.9 }], ['starburst', { points: 9, inner: 0.6, spin: -40 }]],
    strike: [['wave', {}], ['drops', { n: 12, glyph: 'drop', size: 0.45 }]],
    ko: [['speedlines', { color: '#e8f8ff', n: 36, rot: 10 }], ['flash', { big: true }], ['splat', { at: 150, n: 10, color: '#9fdcff' }], ['flood', { at: 300 }],
      ['whirl', { at: 700, n: 4 }], ['ring', { at: 1400, scale: 2.6, color: '#38b6ff', width: 5 }], ['burst', { at: 1400, n: 16, size: 0.8, reach: 1.3 }]],
    koMs: 2300, koPeak: 1400,
    sharpen: [['blade', { angle: 5, n: 2, color: '#e8f8ff', fan: 10 }], ['splat', { n: 4, color: '#9fdcff' }]],
    heavy: [['pillar', { width: 0.6, color: '#38b6ff' }], ['drops', { n: 16, glyph: 'drop', size: 0.5 }], ['quake', { n: 2, color: '#38b6ff' }]],
    block: [['sigil', { sides: 9, turn: 40 }], ['splat', { n: 6, color: '#e8f8ff' }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'drop' }]],
    wind: [['heart', {}], ['gust', { n: 3, color: '#9fdcff', turn: -60 }]],
    body: { hit: 'wobble', crit: 'knock', sharpen: 'gash', strike: 'surge', heavy: 'charge', block: 'reel', shield: 'skid', wind: 'sway', ko: 'founder' },
  },
  lich: {
    color: '#5dff9e', accent: '#062a14', glyph: 'skull',
    hit: [['burst', { n: 4, spin: 180, size: 0.8 }], ['sparks', { n: 8, color: '#b8ffd4' }]],
    crit: [['burst', { n: 8, spin: 240 }], ['ring', { scale: 2.2, dashed: true }], ['starburst', { points: 6, inner: 0.25, spin: 60 }]],
    strike: [['projectile', { glyph: 'skull' }], ['ring', { scale: 2.4, width: 6 }], ['vignette', { color: '#2bd46f' }]],
    ko: [['speedlines', { color: '#b8ffd4', n: 40, rot: 11 }], ['flash', { big: true }], ['gem', { at: 150 }], ['crack', { at: 450, n: 6, color: '#b8ffd4' }],
      ['shards', { at: 1300, n: 16, color: '#5dff9e', reach: 1.3 }], ['ring', { at: 1350, color: '#5dff9e', scale: 2.6, width: 6 }], ['burst', { at: 1350, glyph: 'bone', n: 12, spin: 500, reach: 1.3 }], ['rise', { at: 1450, n: 12, glyph: 'wisp', color: '#5dff9e' }]],
    koMs: 2300, koPeak: 1350,
    sharpen: [['blade', { angle: 50, n: 2, color: '#b8ffd4' }], ['burst', { n: 6, glyph: 'bone', size: 0.5, spin: 600 }]],
    heavy: [['pull', { n: 12, glyph: 'skull' }], ['ring', { color: '#5dff9e', scale: 2.6, width: 6 }], ['quake', { n: 2, color: '#2bd46f' }]],
    block: [['sigil', { sides: 5, rot: 36, turn: 72 }], ['shards', { n: 8, color: '#5dff9e' }]],
    shield: [['bubble', {}], ['deflect', { n: 5, glyph: 'skull' }]],
    wind: [['heart', {}], ['rise', { n: 8, glyph: 'wisp', color: '#b8ffd4', size: 0.6 }], ['gust', { n: 2, color: '#5dff9e', turn: 100 }]],
    body: { hit: 'flicker', crit: 'jolt', sharpen: 'split', strike: 'cast', heavy: 'loom', block: 'jar', shield: 'rebuff', wind: 'shrink', ko: 'unbound' },
  },
  cerberus: {
    color: '#3fffd5', accent: '#06302a', glyph: 'chain',
    hit: [['burst', { n: 5, spin: 200, size: 0.8 }], ['sparks', { n: 8, color: '#ff8a3a' }]],
    crit: [['lash', { small: true }], ['burst', { n: 9, spin: 260 }], ['starburst', { points: 3, inner: 0.3, spin: -120 }]],
    strike: [['lash', {}], ['bite', { n: 3, dir: 'v', small: true }]],
    ko: [['speedlines', { color: '#ff8a3a', n: 34, rot: 12 }], ['flash', { big: true }], ['chainsnap', { at: 200 }], ['sparks', { at: 780, n: 14, color: '#3fffd5' }],
      ['gutter', { at: 900, color: '#3fffd5' }], ['ring', { at: 1300, scale: 2.5, color: '#3fffd5' }], ['burst', { at: 1300, glyph: 'chain', n: 14, spin: 600, reach: 1.4 }], ['dust', { at: 1350, n: 12 }]],
    koMs: 2200, koPeak: 1300,
    sharpen: [['blade', { angle: -15, n: 3, color: '#ff8a3a', fan: 20 }], ['sparks', { n: 8, color: '#3fffd5' }]],
    heavy: [['rise', { n: 14, glyph: 'flame', size: 0.6, color: '#ff8a3a' }], ['claws', { n: 3, angle: 20, color: '#3fffd5' }], ['quake', { n: 2, color: '#ff8a3a' }]],
    block: [['sigil', { sides: 3, turn: 60 }], ['burst', { n: 6, glyph: 'chain', size: 0.6, spin: 300 }]],
    shield: [['bubble', {}], ['deflect', { n: 3, glyph: 'chain', from: 'side' }], ['sparks', { n: 6, color: '#ff8a3a' }]],
    wind: [['heart', {}], ['rise', { n: 6, glyph: 'flame', size: 0.5, color: '#3fffd5' }], ['gust', { n: 3, color: '#3fffd5', turn: -75 }]],
    body: { hit: 'reel', crit: 'knock', sharpen: 'gash', strike: 'rear', heavy: 'pounce', block: 'stumble', shield: 'ricochet', wind: 'falter', ko: 'unchained' },
  },
  tempest: {
    color: '#9fd8ff', accent: '#ffffff', glyph: 'bolt',
    hit: [['burst', { n: 5, spin: 30 }], ['sparks', { n: 10, color: '#e6f6ff' }]],
    crit: [['bolt', { n: 1 }], ['burst', { n: 9 }], ['starburst', { points: 4, inner: 0.15, spin: 20 }]],
    strike: [['bolt', { n: 3 }], ['vignette', { color: '#7cc8ff' }]],
    ko: [['speedlines', { color: '#e6f6ff', n: 50, rot: 13 }], ['flash', { big: true }], ['bolt', { at: 100, n: 5 }], ['bolt', { at: 700, n: 2 }],
      ['smoke', { at: 850, dir: 'out', color: '#b4c2d2', n: 12, size: 0.75 }], ['sparks', { at: 1150, n: 18, color: '#e6f6ff', reach: 1.4 }], ['ring', { at: 1150, scale: 2.8, width: 6 }], ['drops', { at: 1250, n: 18, glyph: 'drop', size: 0.35, color: '#9fd8ff' }]],
    koMs: 2100, koPeak: 1150,
    sharpen: [['blade', { angle: -80, n: 2, color: '#ffffff', ms: 340 }], ['bolt', { n: 1 }]],
    heavy: [['beam', { dir: 'down', width: 0.4, color: '#e6f6ff' }], ['sparks', { n: 20, color: '#e6f6ff', reach: 1.3 }], ['quake', { n: 2, color: '#9fd8ff' }], ['vignette', { color: '#3d7cff' }]],
    block: [['sigil', { sides: 6, rot: 30, turn: 90 }], ['sparks', { n: 14, color: '#e6f6ff', reach: 1.3 }]],
    shield: [['bubble', {}], ['deflect', { n: 5, glyph: 'bolt' }]],
    wind: [['heart', {}], ['gust', { n: 4, color: '#e6f6ff', turn: 120 }]],
    body: { hit: 'flinch', crit: 'jolt', sharpen: 'sever', strike: 'cast', heavy: 'quake', block: 'recoil', shield: 'glance', wind: 'sway', ko: 'burnout' },
  },
  dreamer: {
    color: '#ff5cf0', accent: '#ffffff', glyph: 'bubble',
    hit: [['burst', { n: 6, size: 0.8 }], ['ring', { color: '#ffb3f7' }]],
    crit: [['tendrils', { n: 2 }], ['burst', { n: 10 }], ['starburst', { points: 7, inner: 0.65, spin: 200 }]],
    strike: [['tendrils', { n: 4 }], ['vignette', { color: '#c23cff' }]],
    ko: [['speedlines', { color: '#ffb3f7', n: 28, rot: 14 }], ['flash', { big: true }], ['bubbles', { at: 150 }], ['burst', { at: 1150, n: 20, reach: 1.4, size: 0.9 }],
      ['ring', { at: 1150, scale: 2.4, dashed: true, color: '#ff5cf0' }], ['glint', { at: 1200, n: 8, color: '#ffffff' }], ['rise', { at: 1250, n: 12, glyph: 'bubble', size: 0.6 }]],
    koMs: 2100, koPeak: 1150,
    sharpen: [['blade', { angle: 30, n: 3, color: '#ffb3f7', fan: 50 }], ['glint', { n: 6, color: '#ffffff' }]],
    heavy: [['pull', { n: 16, glyph: 'bubble' }], ['scream', { n: 3, color: '#ff5cf0', inward: true }], ['quake', { n: 2, color: '#c23cff' }]],
    block: [['sigil', { sides: 8, rot: 22, turn: -80 }], ['burst', { n: 8, glyph: 'bubble', size: 0.6 }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'bubble', from: 'side' }]],
    wind: [['heart', {}], ['pulse', { color: '#ff5cf0' }], ['rise', { n: 5, glyph: 'bubble', size: 0.4 }]],
    body: { hit: 'wobble', crit: 'twirl', sharpen: 'split', strike: 'surge', heavy: 'loom', block: 'rebound', shield: 'rebuff', wind: 'sway', ko: 'popped' },
  },
  berserker: {
    color: '#ff4a1a', accent: '#2a0a00', glyph: 'axe',
    hit: [['sparks', { n: 10, color: '#ffb36a' }], ['burst', { n: 4, size: 0.8, spin: 300 }]],
    crit: [['cleave', { small: true }], ['sparks', { n: 16, color: '#ffb36a' }], ['starburst', { points: 9, inner: 0.3, spin: -25 }]],
    strike: [['cleave', {}], ['rise', { n: 8, glyph: 'ember', size: 0.35 }], ['vignette', {}]],
    ko: [['speedlines', { color: '#ffb36a', n: 46, rot: 15 }], ['flash', { big: true }], ['rise', { at: 100, n: 18, glyph: 'ember', size: 0.45 }], ['axefall', { at: 650 }],
      ['crack', { at: 1300, n: 7, color: '#ffb36a' }], ['dust', { at: 1300, n: 16 }], ['ring', { at: 1350, scale: 2.6, color: '#ff4a1a', width: 7 }], ['drops', { at: 1400, n: 14, glyph: 'ember', size: 0.4, color: '#7a2a10' }]],
    koMs: 2200, koPeak: 1350,
    sharpen: [['blade', { angle: -40, n: 2, color: '#ffb36a', fan: 80 }], ['sparks', { n: 14, color: '#ffe0a0' }]],
    heavy: [['claws', { n: 4, angle: 30, color: '#ff4a1a' }], ['quake', { n: 3, rubble: 8 }], ['rise', { n: 12, glyph: 'ember', size: 0.4 }]],
    block: [['sigil', { sides: 4, turn: 45 }], ['sparks', { n: 16, color: '#ffb36a' }]],
    shield: [['bubble', {}], ['deflect', { n: 4, glyph: 'axe' }]],
    wind: [['heart', {}], ['dust', { n: 8, color: '#ff8a5a' }], ['gust', { n: 2, color: '#ff4a1a', turn: 160 }]],
    body: { hit: 'reel', crit: 'buckle', sharpen: 'carve', strike: 'slam', heavy: 'overreach', block: 'stumble', shield: 'ricochet', wind: 'falter', ko: 'lastStand' },
  },
  inferno: {
    color: '#ff7a14', accent: '#ffe08a', glyph: 'flame',
    hit: [['burst', { n: 6, size: 0.8 }], ['rise', { n: 6, glyph: 'ember', size: 0.35 }]],
    crit: [['shards', { n: 10, color: '#ffe08a' }], ['burst', { n: 10 }], ['starburst', { points: 11, inner: 0.45, spin: 80 }]],
    strike: [['breath', {}], ['rise', { n: 10, glyph: 'ember', size: 0.4 }]],
    ko: [['speedlines', { color: '#ffe08a', n: 38, rot: 16 }], ['flash', { big: true }], ['pillar', { at: 100, width: 0.6, color: '#ff7a14' }], ['rise', { at: 300, n: 18, glyph: 'flame', size: 0.7 }],
      ['smoke', { at: 1000, color: '#6a5f66', n: 14, size: 0.9 }], ['embers', { at: 1050 }], ['burst', { at: 1350, glyph: 'ember', n: 14, size: 0.6, reach: 1.4 }], ['ring', { at: 1350, color: '#ffe08a', scale: 2.4 }], ['sparks', { at: 1400, n: 12, color: '#ffb000' }]],
    koMs: 2300, koPeak: 1350,
    sharpen: [['blade', { angle: 15, n: 2, color: '#ffe08a' }], ['rise', { n: 6, glyph: 'ember', size: 0.3 }]],
    heavy: [['beam', { dir: 'down', width: 0.7, color: '#ff4a1a' }], ['drops', { n: 14, glyph: 'flame', size: 0.6 }], ['quake', { n: 2, color: '#ffe08a' }]],
    block: [['sigil', { sides: 6, turn: -30 }], ['burst', { n: 8, glyph: 'ember', size: 0.5 }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'flame', from: 'side' }]],
    wind: [['heart', {}], ['gust', { n: 3, color: '#ffe08a', turn: -120 }]],
    body: { hit: 'flinch', crit: 'stun', sharpen: 'nick', strike: 'lunge', heavy: 'charge', block: 'jar', shield: 'skid', wind: 'dim', ko: 'gutterOut' },
  },
  swarmqueen: {
    color: '#ffb21a', accent: '#5a2d00', glyph: 'hex',
    hit: [['burst', { n: 6, size: 0.7 }], ['volley', { n: 5, small: true }]],
    crit: [['volley', { n: 10, small: true }], ['burst', { n: 10 }], ['starburst', { points: 6, inner: 0.7, spin: 30 }]],
    strike: [['volley', { n: 16 }], ['vignette', { color: '#ffb21a' }]],
    ko: [['speedlines', { color: '#ffe08a', n: 32, rot: 17 }], ['flash', { big: true }], ['volley', { at: 150, n: 12, scatter: true }], ['swarm', { at: 450 }],
      ['burst', { at: 1250, n: 18, reach: 1.4, spin: 200 }], ['ring', { at: 1250, scale: 2.4, color: '#ffb21a' }], ['dust', { at: 1300, n: 12, color: '#ffd27a' }]],
    koMs: 2200, koPeak: 1250,
    sharpen: [['blade', { angle: -25, n: 3, color: '#ffe08a', fan: 8, gap: 50 }], ['volley', { n: 6, small: true }]],
    heavy: [['pull', { n: 20 }], ['quake', { n: 1, color: '#ffb21a' }], ['dust', { n: 10, color: '#ffd27a' }]],
    block: [['sigil', { sides: 6, rot: 0, turn: 120 }], ['burst', { n: 6, glyph: 'hex', size: 0.5, spin: 90 }]],
    shield: [['bubble', {}], ['deflect', { n: 8, glyph: 'hex' }]],
    wind: [['heart', {}], ['glint', { n: 6, color: '#ffe08a' }]],
    body: { hit: 'flinch', crit: 'jolt', sharpen: 'nick', strike: 'dart', heavy: 'pounce', block: 'reel', shield: 'ricochet', wind: 'shrink', ko: 'scattered' },
  },
  moonmaw: {
    color: '#c9b8ff', accent: '#20184a', glyph: 'crescent',
    hit: [['burst', { n: 5, spin: 160 }], ['sparks', { n: 8, color: '#f2edff' }]],
    crit: [['talons', { small: true }], ['burst', { n: 9, spin: 200 }], ['starburst', { points: 12, inner: 0.35, spin: -60 }]],
    strike: [['talons', {}], ['burst', { n: 8, glyph: 'feather', size: 0.6, color: '#9a8ad6' }]],
    ko: [['speedlines', { color: '#f2edff', n: 36, rot: 18 }], ['flash', { big: true }], ['eclipse', { at: 200, cross: true, ms: 1350 }], ['diamondring', { at: 1250 }],
      ['rays', { at: 1500, n: 12, color: '#f2edff' }], ['ring', { at: 1500, color: '#c9b8ff', scale: 2.6 }], ['burst', { at: 1550, n: 14, spin: 300, reach: 1.3 }]],
    koMs: 2400, koPeak: 1500,
    sharpen: [['blade', { angle: 60, n: 2, color: '#f2edff', fan: 16 }], ['glint', { n: 5, color: '#c9b8ff' }]],
    heavy: [['beam', { dir: 'cone', width: 1, color: '#c9b8ff' }], ['claws', { n: 3, angle: -35, color: '#f2edff' }], ['quake', { n: 2, color: '#c9b8ff' }]],
    block: [['sigil', { sides: 12, rot: 15, turn: -45 }], ['burst', { n: 6, glyph: 'crescent', size: 0.6 }]],
    shield: [['bubble', {}], ['deflect', { n: 5, glyph: 'crescent' }]],
    wind: [['heart', {}], ['gust', { n: 3, color: '#f2edff', turn: 90 }]],
    body: { hit: 'reel', crit: 'whiplash', sharpen: 'gash', strike: 'swipe', heavy: 'overreach', block: 'recoil', shield: 'glance', wind: 'dim', ko: 'totality' },
  },
  hydra: {
    color: '#5fd0ff', accent: '#062436', glyph: 'fang',
    hit: [['burst', { n: 5, spin: 120, size: 0.8 }], ['splat', { n: 4, color: '#bde9ff' }]],
    crit: [['bite', { n: 1, dir: 'h', small: true }], ['burst', { n: 9 }], ['starburst', { points: 5, inner: 0.6, spin: 144 }]],
    strike: [['bite', { n: 2, dir: 'h' }], ['splat', { n: 8, color: '#bde9ff' }]],
    ko: [['speedlines', { color: '#bde9ff', n: 40, rot: 19 }], ['flash', { big: true }], ['heads', { at: 150 }], ['splat', { at: 950, n: 14, color: '#bde9ff', reach: 1.2 }],
      ['whirl', { at: 1500, n: 2 }], ['ring', { at: 1600, color: '#5fd0ff', scale: 2.6 }], ['burst', { at: 1650, n: 12, spin: 200, reach: 1.3 }]],
    koMs: 2500, koPeak: 1600,
    sharpen: [['blade', { angle: -5, n: 3, color: '#bde9ff', fan: 60 }], ['splat', { n: 3, color: '#bde9ff' }]],
    heavy: [['pillar', { width: 0.45, color: '#5fd0ff' }], ['splat', { n: 12, color: '#bde9ff', big: true }], ['quake', { n: 3, color: '#5fd0ff' }]],
    block: [['sigil', { sides: 5, rot: 0, turn: 144 }], ['burst', { n: 6, glyph: 'fang', size: 0.6, spin: 120 }]],
    shield: [['bubble', {}], ['deflect', { n: 3, glyph: 'fang', from: 'side' }]],
    wind: [['heart', {}], ['pulse', { color: '#5fd0ff' }], ['gust', { n: 2, color: '#bde9ff', turn: 60 }]],
    body: { hit: 'reel', crit: 'knock', sharpen: 'sever', strike: 'rear', heavy: 'pounce', block: 'stumble', shield: 'skid', wind: 'falter', ko: 'severed' },
  },
  kaleido: {
    color: '#ff8a1a', accent: '#ffffff', glyph: 'shard',
    hit: [['shards', { n: 6, rainbow: true }], ['ring', { color: '#ffffff' }]],
    crit: [['shards', { n: 14, rainbow: true }], ['rays', { n: 12, rainbow: true }], ['starburst', { points: 6, inner: 0.2, spin: 180 }]],
    strike: [['shards', { n: 12, rainbow: true, inward: true }], ['beam', { dir: 'across', width: 0.32, rainbow: true }]],
    ko: [['speedlines', { color: '#ffffff', n: 54, rot: 20 }], ['flash', { big: true }], ['mandala', { at: 100 }], ['crack', { at: 750, n: 10, color: '#ffffff' }],
      ['shards', { at: 1150, n: 28, rainbow: true, reach: 1.5 }], ['rays', { at: 1150, n: 18, rainbow: true }], ['ring', { at: 1200, color: '#ffffff', scale: 2.8, width: 5 }]],
    koMs: 2100, koPeak: 1150,
    sharpen: [['blade', { angle: -50, n: 3, color: '#ffffff', fan: 60, gap: 40 }], ['shards', { n: 8, rainbow: true }]],
    heavy: [['scream', { n: 3, color: '#ff8a1a' }], ['rays', { n: 18, rainbow: true }], ['quake', { n: 2, color: '#ff8a1a' }]],
    block: [['sigil', { sides: 6, rot: 30, turn: 180 }], ['shards', { n: 12, rainbow: true }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'shard' }]],
    wind: [['heart', {}], ['glint', { n: 10, color: '#ffffff', size: 0.7 }]],
    body: { hit: 'flinch', crit: 'twirl', sharpen: 'split', strike: 'cast', heavy: 'quake', block: 'jar', shield: 'rebuff', wind: 'sway', ko: 'refract' },
  },
  puppeteer: {
    color: '#ff3b52', accent: '#1a0006', glyph: 'needle',
    hit: [['burst', { n: 6, spin: 540, size: 0.8 }], ['sparks', { n: 6 }]],
    crit: [['strings', { n: 3 }], ['burst', { n: 10, spin: 720 }], ['starburst', { points: 8, inner: 0.15, spin: 22 }]],
    strike: [['strings', { n: 5, yank: true }], ['projectile', { glyph: 'needle' }]],
    ko: [['speedlines', { color: '#ffb0bc', n: 30, rot: 21 }], ['flash', { big: true }], ['strings', { at: 150, n: 6 }], ['snip', { at: 650 }],
      ['strings', { at: 1050, n: 6, cut: true }], ['burst', { at: 1300, n: 12, spin: 720, reach: 1.3 }], ['dust', { at: 1300, n: 12 }], ['ring', { at: 1350, scale: 2.2, color: '#ff3b52' }]],
    koMs: 2200, koPeak: 1300,
    sharpen: [['blade', { angle: 80, n: 2, color: '#ffb0bc', fan: 12 }], ['strings', { n: 2, cut: true }]],
    heavy: [['volley', { n: 14 }], ['quake', { n: 2 }], ['crack', { n: 5, color: '#ff3b52' }]],
    block: [['sigil', { sides: 4, rot: 0, turn: -90 }], ['strings', { n: 3, cut: true }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'needle' }]],
    wind: [['heart', {}], ['gust', { n: 2, color: '#ffb0bc', turn: -100 }]],
    body: { hit: 'spin', crit: 'whiplash', sharpen: 'sever', strike: 'dart', heavy: 'overreach', block: 'rebound', shield: 'skid', wind: 'falter', ko: 'cutStrings' },
  },
  sugarqueen: {
    color: '#ff5fa2', accent: '#ffffff', glyph: 'candy',
    hit: [['burst', { n: 6, spin: 360, size: 0.8 }], ['confetti', { n: 8, sprinkles: true }]],
    crit: [['splat', { n: 6, color: '#ff9cc7' }], ['burst', { n: 10, spin: 540 }], ['starburst', { points: 10, inner: 0.75, spin: 120 }]],
    strike: [['splat', { n: 10, color: '#ff2f87', big: true }], ['drops', { n: 8, glyph: 'candy', size: 0.5 }]],
    ko: [['speedlines', { color: '#ffffff', n: 24, rot: 22 }], ['flash', { big: true }], ['drip', { at: 150, n: 9, color: '#ff9cc7' }], ['puddle', { at: 600 }],
      ['confetti', { at: 1350, n: 34, sprinkles: true }], ['splat', { at: 1350, n: 10, color: '#ff9cc7', big: true }], ['ring', { at: 1400, scale: 2.4, color: '#ff9cc7' }], ['burst', { at: 1450, n: 12, spin: 720, reach: 1.3 }]],
    koMs: 2300, koPeak: 1350,
    sharpen: [['blade', { angle: 20, n: 3, color: '#ffffff', fan: 22 }], ['confetti', { n: 10, sprinkles: true }]],
    heavy: [['volley', { n: 12 }], ['fountain', { n: 16, glyph: 'candy', size: 0.5 }], ['quake', { n: 2, color: '#ff9cc7' }]],
    block: [['sigil', { sides: 8, rot: 0, turn: 45 }], ['burst', { n: 8, glyph: 'candy', size: 0.5, spin: 500 }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'candy', from: 'side' }]],
    wind: [['heart', {}], ['pulse', { color: '#ff9cc7' }], ['glint', { n: 6, color: '#ffffff', size: 0.7 }]],
    body: { hit: 'wobble', crit: 'buckle', sharpen: 'carve', strike: 'surge', heavy: 'crush', block: 'jar', shield: 'rebuff', wind: 'shrink', ko: 'melted' },
  },
  kitsune: {
    color: '#ff5a7a', accent: '#ffd6e0', glyph: 'petal',
    hit: [['burst', { n: 7, spin: 200, size: 0.7 }], ['sparks', { n: 6, color: '#ffd6e0' }]],
    crit: [['orbit', { n: 3, color: '#7fe8ff' }], ['burst', { n: 12, spin: 300, size: 0.8 }], ['starburst', { points: 9, inner: 0.55, spin: 160 }]],
    strike: [['orbit', { n: 5, color: '#7fe8ff' }], ['vignette', { color: '#ff5a7a' }]],
    ko: [['speedlines', { color: '#7fe8ff', n: 42, rot: 23 }], ['flash', { big: true }], ['tails', { at: 150 }], ['orbit', { at: 1000, n: 6, out: true, color: '#7fe8ff' }],
      ['drops', { at: 1150, n: 26, glyph: 'petal', size: 0.6 }], ['ring', { at: 1450, color: '#7fe8ff', scale: 2.6, dashed: true }], ['burst', { at: 1450, n: 16, spin: 400, reach: 1.4, size: 0.7 }]],
    koMs: 2400, koPeak: 1450,
    sharpen: [['blade', { angle: -30, n: 2, color: '#7fe8ff', fan: 36 }], ['drops', { n: 8, glyph: 'petal', size: 0.45 }]],
    heavy: [['pillar', { width: 0.5, color: '#7fe8ff' }], ['rise', { n: 12, glyph: 'flame', color: '#7fe8ff', size: 0.6 }], ['quake', { n: 2, color: '#ff5a7a' }]],
    block: [['sigil', { sides: 9, rot: 20, turn: 80 }], ['drops', { n: 6, glyph: 'petal', size: 0.5 }]],
    shield: [['bubble', {}], ['deflect', { n: 6, glyph: 'petal' }]],
    wind: [['heart', {}], ['drops', { n: 10, glyph: 'petal', size: 0.4, color: '#ffd6e0' }], ['gust', { n: 3, color: '#7fe8ff', turn: -170 }]],
    body: { hit: 'flinch', crit: 'twirl', sharpen: 'gash', strike: 'cast', heavy: 'charge', block: 'rebound', shield: 'glance', wind: 'sway', ko: 'foxfire' },
  },
  ophanim: {
    color: '#ffcf4a', accent: '#5a3a00', glyph: 'eye',
    hit: [['burst', { n: 5, size: 0.8 }], ['halo', { n: 1, small: true }]],
    crit: [['halo', { n: 2 }], ['burst', { n: 9 }], ['starburst', { points: 16, inner: 0.55, spin: 45 }]],
    strike: [['halo', { n: 3, slice: true }], ['beam', { dir: 'down', width: 0.3, color: '#ff9d00' }]],
    ko: [['speedlines', { color: '#fff6c8', n: 60, rot: 24 }], ['flash', { big: true }], ['halo', { at: 150, n: 3, collapse: true }], ['eyeclose', { at: 300 }],
      ['pull', { at: 1000, n: 18 }], ['shards', { at: 1500, n: 16, color: '#ffcf4a' }], ['ring', { at: 1500, color: '#ffcf4a', scale: 2.8, width: 6 }], ['rays', { at: 1550, n: 24, color: '#fff6c8' }]],
    koMs: 2400, koPeak: 1500,
    sharpen: [['blade', { angle: -90, n: 2, color: '#fff6c8', fan: 90 }], ['halo', { n: 1, small: true }]],
    heavy: [['rays', { n: 24, color: '#ffcf4a' }], ['shards', { n: 14, color: '#ffcf4a' }], ['quake', { n: 2 }]],
    block: [['sigil', { sides: 16, turn: 45 }], ['rays', { n: 12, color: '#ffcf4a' }]],
    shield: [['bubble', {}], ['deflect', { n: 5, glyph: 'eye' }]],
    wind: [['heart', {}], ['gust', { n: 3, color: '#fff6c8', turn: -150 }], ['glint', { n: 5 }]],
    body: { hit: 'clank', crit: 'stun', sharpen: 'nick', strike: 'cast', heavy: 'loom', block: 'recoil', shield: 'rebuff', wind: 'dim', ko: 'eyeShut' },
  },
  void: {
    color: '#b067ff', accent: '#ffffff', glyph: 'star4',
    hit: [['burst', { n: 6, spin: 180, size: 0.8 }], ['ring', { color: '#e3c9ff', dashed: true }]],
    crit: [['pull', { n: 10, small: true }], ['burst', { n: 10, spin: 240 }], ['starburst', { points: 4, inner: 0.45, spin: 360 }]],
    strike: [['pull', { n: 16 }], ['tendrils', { n: 3, color: '#6a2bd6' }], ['vignette', { color: '#5a1fb8' }]],
    ko: [['speedlines', { color: '#e3c9ff', n: 44, rot: 25 }], ['flash', { big: true }], ['pull', { at: 100, n: 28 }], ['singularity', { at: 300, color: '#ffc46a' }],
      ['ring', { at: 1350, scale: 2.8, width: 8, color: '#ffffff' }], ['burst', { at: 1350, n: 18, reach: 1.5, spin: 360 }], ['shards', { at: 1400, n: 14, color: '#b067ff' }]],
    koMs: 2300, koPeak: 1350,
    sharpen: [['blade', { angle: 40, n: 3, color: '#e3c9ff', fan: 120 }], ['pull', { n: 8, small: true }]],
    heavy: [['eclipse', {}], ['shards', { n: 14, color: '#b067ff', inward: true }], ['quake', { n: 3, color: '#b067ff' }]],
    block: [['sigil', { sides: 8, rot: 0, turn: 270 }], ['shards', { n: 10, color: '#e3c9ff', inward: true }]],
    shield: [['bubble', {}], ['deflect', { n: 7, glyph: 'star4', from: 'side' }]],
    wind: [['heart', {}], ['gust', { n: 4, color: '#e3c9ff', turn: 200 }]],
    body: { hit: 'flicker', crit: 'jolt', sharpen: 'split', strike: 'surge', heavy: 'quake', block: 'reel', shield: 'ricochet', wind: 'shrink', ko: 'eventHorizon' },
  },
}
// A boss with no style (a newer build's boss): the default look.
export const DEFAULT_IMPACT = {
  color: '#ffd23a', accent: '#1a1020', glyph: 'star4',
  hit: [['burst', { n: 6 }], ['ring', {}]], crit: [['burst', { n: 10 }], ['starburst', {}]], strike: [['claws', { n: 3 }], ['vignette', {}]],
  sharpen: [['blade', {}], ['glint', {}]], heavy: [['quake', {}], ['claws', { n: 5 }]], block: [['sigil', {}], ['sparks', { n: 10 }]],
  shield: [['bubble', {}], ['deflect', {}]], wind: [['heart', {}], ['pulse', {}]],
  ko: [['speedlines', {}], ['flash', { big: true }], ['charge', { at: 150 }], ['burst', { at: 900, n: 14, reach: 1.3 }], ['rays', { at: 900, n: 12 }], ['ring', { at: 950, scale: 2.4 }]],
  koMs: 1900, koPeak: 950,
  body: { hit: 'flinch', crit: 'knock', sharpen: 'gash', strike: 'lunge', heavy: 'pounce', block: 'recoil', shield: 'glance', wind: 'falter', ko: 'fall' },
}
export const impactFor = (motif) => RAID_IMPACT[motif] || DEFAULT_IMPACT

// THE KNOCKOUT'S CLOCK (BossArena's juice and StrikeFxLayer's stamp read it): the cinematic's length, its climax (the
// arena shakes and flashes once more), and the DEFEATED stamp, which slams down KO_STAMP_AFTER ms after the climax
// (landing KO_STAMP_LAND of the way into its own play) and is gone when the cinematic ends.
export const KO_MS_MIN = 1600
export const KO_MS_MAX = 2600
export const KO_STAMP_AFTER = 120
export const KO_STAMP_LAND = 0.09
export function koTiming(motif) {
  const s = impactFor(motif)
  const ms = Math.min(KO_MS_MAX, Math.max(KO_MS_MIN, s.koMs || 1900))
  const peak = Math.min(ms - 700, Math.max(300, s.koPeak || Math.round(ms / 2)))
  const stampAt = peak + KO_STAMP_AFTER
  const stampMs = ms - stampAt
  return { ms, peak, stampAt, stampMs, land: stampAt + Math.round(stampMs * KO_STAMP_LAND) }
}
